# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3cb652b49377b093e672efe432edac7fcf98b8584a4e27b299bc4937aaba6e38dd006a86d40f1621b0048652670e3f6198131649ae0e5047a980d2d19bf3ae35

test:
  secret_key_base: 0ef4ea39054e3ca13929136ca6c9919219657724c9f9bead732d33a1190f4d2f59cdf0be14b8717cc1869a56decbb73a1c2a13e55fbd7565b77555d942e73df8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
